site_name: STETutorial
docs_dir: docs          # 文档源文件目录
site_dir: site          # 构建后输出到 site/
nav:                     # 侧边栏结构
  - install:
     - braincog: braincog.md
     - tasks: tasks.md
  - training:
     - backbone model: backbone.md
     - neuron model: neuron.md
     - training: training.md
     - resources: resources.md
theme:                  # 选择一个简单主题，也可以安装 mkdocs-material
  name: readthedocs